### PR TITLE
Update package-lock.json to new format

### PR DESCRIPTION
**Pull request by rnestler**
Some npm update seemed to change it.

### CODE REVIEW

**Comment by rnestler** [comment]
Should also allow to merge #55 and #56 afterwards.

**Comment by dbrgn** [comment]
Is this lockfile generated with node 10?

**Comment by schmijos** [comment]
@dbrgn Is the node version relevant? The _npm_ version is, right?

**Comment by dbrgn** [comment]
> @dbrgn Is the node version relevant? The npm version is, right?

I was always under the impression that node and npm are somehow bundled / related. If that is not the case, then we're fine :slightly_smiling_face: (I just wanted to make sure that doing "nvm use && npm install" won't revert those changes.)

**Comment by rnestler** [comment]
> Is this lockfile generated with node 10?

Yes node v10.19.0 and npm 6.13.4

**Pull request merged**
