### PR TITLE
Run npm update

### PR DESCRIPTION
**Pull request by dbrgn**
This also updates the lockfile format to v2.

### CODE REVIEW

**Comment by rnestler** [comment]
Which npm version are you using? Locally I get a warning, that my npm doesn't support the v2 format and I'm using the npm version which gets installed by `nvm install`:
```
% nvm install
Found '/home/roughl/projects/gfroerli/web/.nvmrc' with version <14>
v14.17.0 is already installed.
Now using node v14.17.0 (npm v6.14.13)
```

**Comment by dbrgn** [comment]
Yeah, it was a mistake (using the latest npm version). I didn't realize that npm compatibility between different versions was so poor (hello, cargo! 🦀).

I'll have to downgrade the lockfile format for now and stick to the version installed by nvm.

**Comment by dbrgn** [comment]
(Alternatively, we update nvm to node 16.)

**Comment by rnestler** [comment]
> (Alternatively, we update nvm to node 16.)

If it is not much of a hassle (due to incompatibilities etc.) I guess I'd be fine with updating nodejs to 16.

**Comment by dbrgn** [comment]
No, nodejs 16 should work fine! Let's do that instead.

**Pull request merged**
